version: '2'
services:
  spring_boot_project:
    build: spring-boot-project
    ports:
    - "18080:8080"
    - "17071:7071"
  spring_boot_2_project:
    build: spring-boot-2-project
    ports:
    - "28080:8080"
    - "28090:8090"
  prometheus:
    image: "prom/prometheus:v2.4.3"
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus/configuration:/etc/prometheus:ro
    - ./prometheus/data:/prometheus:rw
  grafana:
    image: "grafana/grafana:5.3.2"
    ports:
    - "3000:3000"
