groups:
- name: examples
  rules:

  - alert: ServiceIsDown
    expr: up == 0
    for: 5m
    labels:
      severity: "critical"
    annotations:
      description: "Service {{$labels.instance}} is down."
      summary: "A service is no more reachable."

  - alert: ProcessIsUsingMoreThan1CPU
    expr: rate(process_cpu_seconds_total[1m]) > 1
    for: 5m
    labels:
      severity: "warning"
    annotations:
      description: "Process {{$labels.instance}} is using {{$value}} core."
      summary: "The process uses more than 1 core alone."
