global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files:
  - '/etc/prometheus/alerts/*.yml'

scrape_configs:

  - job_name: 'spring-boot-project'
    dns_sd_configs:
    - names:
      - 'spring_boot_project'
      type: A
      port: 7072

  - job_name: 'spring-boot-2-project'
    metrics_path: /prometheus
    dns_sd_configs:
    - names:
      - 'spring_boot_2_project'
      type: A
      port: 8090
